language: c
dist: bionic

.main: &MAIN
  os:
    - linux
    - osx
  before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make docker-images; fi
  script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -c 'docker run --rm -v $(pwd)/demo-repository:/repository learn-ocaml -- build'; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd tests; sh -c ./runtests.sh; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh .ci-macosx.sh; fi

.docker: &DOCKER
  os: linux
  script:
  - docker build -t "learn-ocaml-${DOCKERFILE#*.}" -f "$DOCKERFILE" .

jobs:
  include:
    - <<: *MAIN
    - env:
      - DOCKERFILE=Dockerfile.test-client
      <<: *DOCKER

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f9e05a2b18ee814cbde2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
