language: c
os:
  - linux
  - osx
sudo: required
services:
  - docker
before_install:
  - docker build -t learn-ocaml --target program .
script:
  - sh -c 'docker run --rm -v $(pwd)/demo-repository:/repository learn-ocaml -- build'
