language: c

.main: &MAIN
  os: linux
  dist: bionic
  before_install:
    - make docker-images
  script:
    - sh -c 'docker run --rm -v $(pwd)/demo-repository:/repository learn-ocaml -- build'
    - cd tests; sh -c ./runtests.sh

.macos: &MACOS
  os: osx
  script:
    - sh .ci-macosx.sh

.docker: &DOCKER
  os: linux
  dist: bionic
  script:
    - docker build -t "learn-ocaml-${DOCKERFILE#*.}" -f "$DOCKERFILE" .

jobs:
  include:
    - <<: *MAIN
    - <<: *MACOS
    - env:
      - DOCKERFILE=Dockerfile.test-client
      <<: *DOCKER

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f9e05a2b18ee814cbde2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
